### ISSUE TITLE
Touchpad high Y values

### ISSUE THREAD

**Issue by psmolaga96** [HarryVienna/WeatherStation-ESP32-BaseStation#6]
Hi, I'm writing because I tested your code on the Makerfabs 1024x600 display, and when I created my own GUI, I noticed something was wrong with the touchpad. It seemed to register touches slightly lower than expected, so I uncommented the line ESP_LOGI(TAG, "Touchpad_read %d %d", touchpad_x, touchpad_y);. It turned out that at a certain point, the Y value jumps to around 65535. Do you happen to know what might be causing this?

![image](https://github.com/user-attachments/assets/b144a72b-5ea1-4045-a09e-550a9a0a8706)

**Comment by HarryVienna** [comment]
In the MaTouch1024x600 branch there is a component esp_lcd_touch_gt911 with the function touch_gt911_write_resolution. I had the problem that the stored values in the touch controller did not match the display resolution. It is used the function esp_lcd_touch_new_i2c_gt911. It's commented out because you only need it once.

**Comment by psmolaga96** [comment]
> In the MaTouch1024x600 branch there is a component esp_lcd_touch_gt911 with the function touch_gt911_write_resolution. I had the problem that the stored values in the touch controller did not match the display resolution. It is used the function esp_lcd_touch_new_i2c_gt911. It's commented out because you only need it once.

Thank you for your quick response! I really appreciate it.
